1. Import Numpy

In [1]:
import numpy as np

2. Numpy Array: Array with one dimention → Vectors, Two dimentions →
Matrices, Three or more dimentions → Tensors
a. Create numpy array and print it. Use np.array
b. Create a two-dimentional array and print it.
c. Use the shape function to determine the shape of array.
d. Use reshape function to convert vector into matrix and matrix into
vector.

In [2]:
# 2. Numpy Array:
# a. Create numpy array and print it
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:\n", arr1)

# b. Create a two-dimensional array and print it
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)

# c. Use shape function to determine the shape of array
print("Shape of 2D array:", arr2.shape)

# d. Reshape function
reshaped = arr1.reshape(1, 5)
print("Reshaped Array:\n", reshaped)

1D Array:
 [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]
Shape of 2D array: (2, 3)
Reshaped Array:
 [[1 2 3 4 5]]


3. Creating Arrays:
a. Create an array using numpy arange function.
b. Reshape it into a matrix form using reshape function.
c. Create arrays filled with zeros and ones. Use zeros and ones function.
d. Create two arrays with zeros and ones and combine them using:
i. as columns next to each other using column_stack
ii. as rows underneath each other using row_stack

In [3]:
# 3. Creating Arrays

# a. Create an array using arange function
arr3 = np.arange(10)
print("Arange array:\n", arr3)

# b. Reshape it into matrix form
arr3_matrix = arr3.reshape(2, 5)
print("Reshaped matrix:\n", arr3_matrix)

# c. Create arrays filled with zeros and ones
zeros_array = np.zeros((3, 3))
ones_array = np.ones((3, 3))
print("Zeros:\n", zeros_array)
print("Ones:\n", ones_array)

# d. Combine arrays
combined_col = np.column_stack((zeros_array, ones_array))
combined_row = np.row_stack((zeros_array, ones_array))
print("Column stacked:\n", combined_col)
print("Row stacked:\n", combined_row)

Arange array:
 [0 1 2 3 4 5 6 7 8 9]
Reshaped matrix:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Column stacked:
 [[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
Row stacked:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


4. Vectorized Functions:
• Numpy offers a plethora of vectorized functions and operators,
called universal functions.
Vectorized operations are easier to code, easier to read, and result in
faster code.
a. Create a matrix of size 3X4 using arrange.
b. Add 150 to each element.
c. Rise each element to power of 2.
d. Create the array a
## ([[ 2, 4, 6, 8, 10],
## [12, 14, 16, 18, 20],
## [22, 24, 26, 28, 30],
## [32, 34, 36, 38, 40]])
Hint: Use arrange function to create matrix of size 4X5 then apply
addition and multiplication operators.
e. Use comparison operators (a>6, a==10)
f. Use logical operators. ((a < 3) | (a > 8)), ((a > 4) & (a < 7)), (~(a > 6))

In [4]:
# 4. Vectorized Functions

# a. Create a matrix of size 3X4 using arrange
matrix = np.arange(12).reshape(3, 4)
print("3x4 Matrix:\n", matrix)

# b. Add 150 to each element
matrix_added = matrix + 150
print("Added 150:\n", matrix_added)

# c. Square each element
matrix_squared = np.power(matrix, 2)
print("Squared:\n", matrix_squared)

# d. Create the given array
a = np.arange(2, 42, 2).reshape(4, 5)
print("Custom matrix:\n", a)

# e. Use comparison operators
print("Elements > 6:\n", a > 6)
print("Elements == 10:\n", a == 10)

# f. Logical operators
print("Logical OR:\n", (a < 3) | (a > 8))
print("Logical AND:\n", (a > 4) & (a < 7))
print("Logical NOT:\n", ~(a > 6))

3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Added 150:
 [[150 151 152 153]
 [154 155 156 157]
 [158 159 160 161]]
Squared:
 [[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
Custom matrix:
 [[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]
Elements > 6:
 [[False False False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
Elements == 10:
 [[False False False False  True]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
Logical OR:
 [[ True False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]
Logical AND:
 [[False False  True False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
Logical NOT:
 [[ True  True  True False False]
 [False False False False False]
 [False False False False False]
 [False Fa

5. Array Indexing and Slicing - Position: Indexing refer to extracting elements
based on their position or certain criteria. This is one of the fundamental
operations with arrays.
a. Create an array with 12 elements.
b. Make all elements from index 7 to 11 to -1.
c. Extract elements at index 2,3,6 positions in one go.
d. Create a matrix of size 3X4.
e. Extract 2nd row
f. Extract 3rd column
g. Extract 1st, 2nd row
h. Extract 2nd row, 3rd column
i. Extract 1s, 2nd row, first three columns
j. set the third row to 1,2,3,4

In [9]:
# 5. Array Indexing and Slicing - Position

# a. Create an array with 12 elements
arr4 = np.arange(12)
print("Array:\n", arr4)

# b. Modify elements
arr4[7:11] = -1
print("Modified array:\n", arr4)

# c. Extract elements at index 2,3,6
print("Extracted elements:\n", arr4[[2, 3, 6]])

# d. Create a 3X4 matrix
matrix2 = np.arange(12).reshape(3, 4)
print("3x4 Matrix:\n", matrix2)

# e. Extract rows and columns
print("2nd row:\n", matrix2[1])
print("3rd column:\n", matrix2[:, 2])
print("1st, 2nd row:\n", matrix2[:2])
print("2nd row, 3rd column:\n", matrix2[1, 2])
print("1st, 2nd row, first 3 columns:\n", matrix2[:2, :3])

# j. Set the third row to 1,2,3,4

matrix2[2] = [1, 2, 3, 4]
print("Modified matrix:\n", matrix2)

Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Modified array:
 [ 0  1  2  3  4  5  6 -1 -1 -1 -1 11]
Extracted elements:
 [2 3 6]
3x4 Matrix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2nd row:
 [4 5 6 7]
3rd column:
 [ 2  6 10]
1st, 2nd row:
 [[0 1 2 3]
 [4 5 6 7]]
2nd row, 3rd column:
 6
1st, 2nd row, first 3 columns:
 [[0 1 2]
 [4 5 6]]
Modified matrix:
 [[0 1 2 3]
 [4 5 6 7]
 [1 2 3 4]]


6. Array Indexing and Slicing – Criteria
a. Create two vectors:
i. names = np.array(["Rahul", "Simran", "Ritesh", "Simran",
"Rahul"])
ii. score = np.array([126, 115, 130, 141, 132])
b. Extract all test scores that are smaller than 130
c. Extract all test scores by Simran
d. Add 10 points to Rahul’s scores.

In [7]:
# 6. Array Indexing and Slicing – Criteria

names = np.array(["Rahul", "Simran", "Ritesh", "Simran", "Rahul"])
scores = np.array([126, 115, 130, 141, 132])

# b. Extract scores < 130
print("Scores < 130:\n", scores[scores < 130])

# c. Extract Simran’s scores
print("Simran's scores:\n", scores[names == "Simran"])

# d. Add 10 points to Rahul's scores
scores[names == "Rahul"] += 10
print("Updated scores:\n", scores)

Scores < 130:
 [126 115]
Simran's scores:
 [115 141]
Updated scores:
 [136 115 130 141 142]


7. Random Numbers:
    a. Explore random.choice
    b. Explore random.normals
    c. Explore random.binomial
    d. Explore random.uniform
    e. Explore and explain the use of random.seed

In [8]:
# 7. Random Numbers
print("Random choice:\n", np.random.choice(scores))
print("Random normal:\n", np.random.normal(size=5))
print("Random binomial:\n", np.random.binomial(10, 0.5, 5))
print("Random uniform:\n", np.random.uniform(0, 10, 5))

# Using random seed
np.random.seed(42)
print("Random number with seed:\n", np.random.rand())

Random choice:
 136
Random normal:
 [ 0.28703292  0.52552664 -0.92754934 -0.30953096  0.2618955 ]
Random binomial:
 [5 6 4 8 4]
Random uniform:
 [2.57549355 6.47136616 3.27979813 4.72864556 7.18835179]
Random number with seed:
 0.3745401188473625


8. Statistical Functions: (sum, mean, median, etc...)
a. Create a matrix of size 3X4
b. Find the sum of all elements
c. Add rows, preserve columns
d. Add columns, preserve rows
Note: a.sum and np.sum(a) are same.

In [10]:
# 8. Statistical Functions

# a. Creating matrix
mat3 = np.random.randint(1, 100, size=(3, 4))
print("Matrix:\n", mat3)

# b. Sum of all elements
print("Sum:\n", mat3.sum())

# c. Sum across rows
print("Sum across rows:\n", mat3.sum(axis=1))

# d. Sum across columns
print("Sum across columns:\n", mat3.sum(axis=0))

Matrix:
 [[93 15 72 61]
 [21 83 87 75]
 [75 88 24  3]]
Sum:
 697
Sum across rows:
 [241 266 190]
Sum across columns:
 [189 186 183 139]
